# Generated by Django 6.1 on 2026-09-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('selected_course', models.CharField(choices=[('python_fs', 'Python Full Stack Development'), ('java_fs', 'Java Full Stack Development'), ('data_analytics', 'Data Analytics & Power BI'), ('ai_ml', 'AI & Machine Learning'), ('cloud_devops', 'Cloud & DevOps')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
